Fix building static libs
libspatialindex/libspatialindex pull request #223
Opened 2021-05-22 16:04 UTC by m-kuhn

Port of https://github.com/microsoft/vcpkg/pull/17506

2021-05-23 05:47 UTC, m-kuhn commented
I don't understand the connection between the changes in here and the c++20 build errors. :thinking:

2021-05-23 23:55 UTC, mwtoews requested changes
Here are a few suggested edits. Other changes are welcome!

As for the C++20 errors, these are Clang issues with their `-std=c++2a` partial C++20 support.

2021-05-23 23:55 UTC, mwtoews commented on src/CMakeLists.txt
> +  target_compile_definitions(spatialindex_c PRIVATE -DSIDX_DLL_IMPORT=1)
Awesome to remove custom `WITH_STATIC_SIDX`, as a global `BUILD_SHARED_LIBS` is preferred.

Two minor nits about style: no space after the `if` command, and use a multiple of two space indents (not one).

2021-05-24 05:17 UTC, m-kuhn commented
Thanks for the suggestions, pr adjusted.
Do the header changes look good to you?

2021-05-24 06:20 UTC, mwtoews approved these changes
Thanks, looks good!

Static Windows builds should eventually be brought into the CI jobs.

2021-05-24 12:31 UTC, m-kuhn commented
> Static Windows builds should eventually be brought into the CI jobs.

Tried to do sobut it doesn't appear yet. Does it only run when it's on master?

2022-02-22 21:55 UTC, hobu commented
I have refactored away from AzP to use GitHub Actions. Please update this PR to catch up and get it ✅ if you are interested in it be including in the next release.

2022-02-23 08:02 UTC, m-kuhn commented
I am away from a keyboard until June, so I am afraid I cannot do a lot this time. If someone could merge master into this branch I would at least have the gh workflow file to edit around, the patch should be trivial enough to do on a mobile device.

2022-02-23 15:41 UTC, hobu commented
> I am away from a keyboard until June, so I am afraid I cannot do a lot this time. 

It's ok. It is very unlikely there will be a release by June anyway 😄  We will leave this open and someone can pick it up.

2022-06-14 04:50 UTC, m-kuhn commented
I tried to add the required github workflow matrix magic, fingers crossed that's how it works

2022-06-16 19:55 UTC, hobu commented
CI failing https://github.com/libspatialindex/libspatialindex/actions/runs/2492840442

2022-06-17 16:04 UTC, merged